//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolio_manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Trade
    {
        public int Id { get; set; }
        public short Direction { get; set; }
        public int Quantity { get; set; }
        public double Tradeprice { get; set; }
        public int Entity_instrumentId { get; set; }
    
        public virtual Entity_instrument Entity_instrument { get; set; }
    }
}
