//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolio_manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entity_instrument()
        {
            this.Entity_Trade = new HashSet<Entity_Trade>();
        }
    
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string Exchange { get; set; }
        public string CompanyName { get; set; }
        public double Underlying { get; set; }
        public string Strike { get; set; }
        public Nullable<double> Tenor { get; set; }
        public string Type { get; set; }
        public int Entity_rateId { get; set; }
        public string Instype { get; set; }
        public Nullable<double> Barrier { get; set; }
        public Nullable<double> Rebate { get; set; }
    
        public virtual Entity_rate Entity_rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_Trade> Entity_Trade { get; set; }
    }
}
