//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolio_manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyEntityModelContainer : DbContext
    {
        public MyEntityModelContainer()
            : base("name=MyEntityModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entity_rate> Entity_rate { get; set; }
        public virtual DbSet<Entity_Trade> Entity_Trade { get; set; }
        public virtual DbSet<Entity_instrument> Entity_instrument { get; set; }
        public virtual DbSet<Entity_Historyprice> Entity_Historyprice { get; set; }
    }
}
